# Generated by Django 4.2 on 2024-05-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inmueble_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default=0, max_length=200),
        ),
    ]
