# Generated by Django 4.2 on 2024-05-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_m2_construidos_inmueble_m2_construido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre_inmueble',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='nombre_region',
            field=models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapaca', 'Tarapaca'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaiso', 'Valparaiso'), ('Metropolitana', 'Metropolitana'), ('OHiggins', 'OHiggins'), ('Maule', 'Maule'), ('Nuble', 'Nuble'), ('Biobio', 'Biobio'), ('La Araucania', 'La Araucania'), ('Los Rios', 'Los Rios'), ('Los Lagos', 'Los Lagos'), ('Aysen', 'Aysen'), ('Magallanes', 'Magallanes')], max_length=50),
        ),
    ]
