# Generated by Django 4.2 on 2024-05-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_inmueble_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default='Sin Desccripcion', max_length=200),
        ),
    ]
