# Generated by Django 4.2 on 2024-06-05 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inmueble_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(default='Sin Descripcion', max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.URLField(default='Ingresar url'),
        ),
    ]
